//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Coinsk__BackingFieldField;
        
        private long IDk__BackingFieldField;
        
        private string Logink__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Coins>k__BackingField", IsRequired=true)]
        public int Coinsk__BackingField {
            get {
                return this.Coinsk__BackingFieldField;
            }
            set {
                if ((this.Coinsk__BackingFieldField.Equals(value) != true)) {
                    this.Coinsk__BackingFieldField = value;
                    this.RaisePropertyChanged("Coinsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public long IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Login>k__BackingField", IsRequired=true)]
        public string Logink__BackingField {
            get {
                return this.Logink__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Logink__BackingFieldField, value) != true)) {
                    this.Logink__BackingFieldField = value;
                    this.RaisePropertyChanged("Logink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Crossword", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
    [System.SerializableAttribute()]
    public partial class Crossword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private long OwnerIDk__BackingFieldField;
        
        private string OwnerLogink__BackingFieldField;
        
        private string Themek__BackingFieldField;
        
        private Client.ClientService.QuestionAnswer[] questionsk__BackingFieldField;
        
        private Client.ClientService.Crossword.ThemeE themeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public long IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OwnerID>k__BackingField", IsRequired=true)]
        public long OwnerIDk__BackingField {
            get {
                return this.OwnerIDk__BackingFieldField;
            }
            set {
                if ((this.OwnerIDk__BackingFieldField.Equals(value) != true)) {
                    this.OwnerIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("OwnerIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OwnerLogin>k__BackingField", IsRequired=true)]
        public string OwnerLogink__BackingField {
            get {
                return this.OwnerLogink__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerLogink__BackingFieldField, value) != true)) {
                    this.OwnerLogink__BackingFieldField = value;
                    this.RaisePropertyChanged("OwnerLogink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Theme>k__BackingField", IsRequired=true)]
        public string Themek__BackingField {
            get {
                return this.Themek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Themek__BackingFieldField, value) != true)) {
                    this.Themek__BackingFieldField = value;
                    this.RaisePropertyChanged("Themek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<questions>k__BackingField", IsRequired=true)]
        public Client.ClientService.QuestionAnswer[] questionsk__BackingField {
            get {
                return this.questionsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.questionsk__BackingFieldField, value) != true)) {
                    this.questionsk__BackingFieldField = value;
                    this.RaisePropertyChanged("questionsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.ClientService.Crossword.ThemeE theme {
            get {
                return this.themeField;
            }
            set {
                if ((this.themeField.Equals(value) != true)) {
                    this.themeField = value;
                    this.RaisePropertyChanged("theme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Crossword.ThemeE", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
        public enum ThemeE : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Sport = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Animals = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Other = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Auto = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Georaphy = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            History = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Music = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Informatic = 8,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionAnswer", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
    [System.SerializableAttribute()]
    public partial class QuestionAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Answerk__BackingFieldField;
        
        private string Questionk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Answer>k__BackingField", IsRequired=true)]
        public string Answerk__BackingField {
            get {
                return this.Answerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Answerk__BackingFieldField, value) != true)) {
                    this.Answerk__BackingFieldField = value;
                    this.RaisePropertyChanged("Answerk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Question>k__BackingField", IsRequired=true)]
        public string Questionk__BackingField {
            get {
                return this.Questionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Questionk__BackingFieldField, value) != true)) {
                    this.Questionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Questionk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.IDBConnection")]
    public interface IDBConnection {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetSum", ReplyAction="http://tempuri.org/IDBConnection/GetSumResponse")]
        int GetSum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetSum", ReplyAction="http://tempuri.org/IDBConnection/GetSumResponse")]
        System.Threading.Tasks.Task<int> GetSumAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetDiff", ReplyAction="http://tempuri.org/IDBConnection/GetDiffResponse")]
        int GetDiff(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetDiff", ReplyAction="http://tempuri.org/IDBConnection/GetDiffResponse")]
        System.Threading.Tasks.Task<int> GetDiffAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetTableData", ReplyAction="http://tempuri.org/IDBConnection/GetTableDataResponse")]
        string GetTableData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/GetTableData", ReplyAction="http://tempuri.org/IDBConnection/GetTableDataResponse")]
        System.Threading.Tasks.Task<string> GetTableDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/signUpUser", ReplyAction="http://tempuri.org/IDBConnection/signUpUserResponse")]
        int signUpUser(string name, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/signUpUser", ReplyAction="http://tempuri.org/IDBConnection/signUpUserResponse")]
        System.Threading.Tasks.Task<int> signUpUserAsync(string name, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/SignInUser", ReplyAction="http://tempuri.org/IDBConnection/SignInUserResponse")]
        Client.ClientService.User SignInUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/SignInUser", ReplyAction="http://tempuri.org/IDBConnection/SignInUserResponse")]
        System.Threading.Tasks.Task<Client.ClientService.User> SignInUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getCrosswords", ReplyAction="http://tempuri.org/IDBConnection/getCrosswordsResponse")]
        Client.ClientService.Crossword[] getCrosswords(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getCrosswords", ReplyAction="http://tempuri.org/IDBConnection/getCrosswordsResponse")]
        System.Threading.Tasks.Task<Client.ClientService.Crossword[]> getCrosswordsAsync(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/createCrossword", ReplyAction="http://tempuri.org/IDBConnection/createCrosswordResponse")]
        int createCrossword(Client.ClientService.Crossword cw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/createCrossword", ReplyAction="http://tempuri.org/IDBConnection/createCrosswordResponse")]
        System.Threading.Tasks.Task<int> createCrosswordAsync(Client.ClientService.Crossword cw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getThemes", ReplyAction="http://tempuri.org/IDBConnection/getThemesResponse")]
        string[] getThemes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getThemes", ReplyAction="http://tempuri.org/IDBConnection/getThemesResponse")]
        System.Threading.Tasks.Task<string[]> getThemesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getUserCrosswords", ReplyAction="http://tempuri.org/IDBConnection/getUserCrosswordsResponse")]
        Client.ClientService.Crossword[] getUserCrosswords(int id, int offset, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getUserCrosswords", ReplyAction="http://tempuri.org/IDBConnection/getUserCrosswordsResponse")]
        System.Threading.Tasks.Task<Client.ClientService.Crossword[]> getUserCrosswordsAsync(int id, int offset, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/insertQuestions", ReplyAction="http://tempuri.org/IDBConnection/insertQuestionsResponse")]
        int insertQuestions(Client.ClientService.QuestionAnswer[] items, int owner_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/insertQuestions", ReplyAction="http://tempuri.org/IDBConnection/insertQuestionsResponse")]
        System.Threading.Tasks.Task<int> insertQuestionsAsync(Client.ClientService.QuestionAnswer[] items, int owner_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getCrosswordQuestions", ReplyAction="http://tempuri.org/IDBConnection/getCrosswordQuestionsResponse")]
        Client.ClientService.QuestionAnswer[] getCrosswordQuestions(int crosswirdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/getCrosswordQuestions", ReplyAction="http://tempuri.org/IDBConnection/getCrosswordQuestionsResponse")]
        System.Threading.Tasks.Task<Client.ClientService.QuestionAnswer[]> getCrosswordQuestionsAsync(int crosswirdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/saveUsersCoins", ReplyAction="http://tempuri.org/IDBConnection/saveUsersCoinsResponse")]
        void saveUsersCoins(long userId, int coins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/saveUsersCoins", ReplyAction="http://tempuri.org/IDBConnection/saveUsersCoinsResponse")]
        System.Threading.Tasks.Task saveUsersCoinsAsync(long userId, int coins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/filterCrosswordsByTheme", ReplyAction="http://tempuri.org/IDBConnection/filterCrosswordsByThemeResponse")]
        Client.ClientService.Crossword[] filterCrosswordsByTheme(int offset, int count, int themeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/filterCrosswordsByTheme", ReplyAction="http://tempuri.org/IDBConnection/filterCrosswordsByThemeResponse")]
        System.Threading.Tasks.Task<Client.ClientService.Crossword[]> filterCrosswordsByThemeAsync(int offset, int count, int themeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/findCrosswords", ReplyAction="http://tempuri.org/IDBConnection/findCrosswordsResponse")]
        Client.ClientService.Crossword[] findCrosswords(int offset, int count, string crosswordName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/findCrosswords", ReplyAction="http://tempuri.org/IDBConnection/findCrosswordsResponse")]
        System.Threading.Tasks.Task<Client.ClientService.Crossword[]> findCrosswordsAsync(int offset, int count, string crosswordName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/filterUserCrosswordsByTheme", ReplyAction="http://tempuri.org/IDBConnection/filterUserCrosswordsByThemeResponse")]
        Client.ClientService.Crossword[] filterUserCrosswordsByTheme(int id, int offset, int length, int themeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/filterUserCrosswordsByTheme", ReplyAction="http://tempuri.org/IDBConnection/filterUserCrosswordsByThemeResponse")]
        System.Threading.Tasks.Task<Client.ClientService.Crossword[]> filterUserCrosswordsByThemeAsync(int id, int offset, int length, int themeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/countCrosswords", ReplyAction="http://tempuri.org/IDBConnection/countCrosswordsResponse")]
        int countCrosswords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnection/countCrosswords", ReplyAction="http://tempuri.org/IDBConnection/countCrosswordsResponse")]
        System.Threading.Tasks.Task<int> countCrosswordsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBConnectionChannel : Client.ClientService.IDBConnection, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBConnectionClient : System.ServiceModel.ClientBase<Client.ClientService.IDBConnection>, Client.ClientService.IDBConnection {
        
        public DBConnectionClient() {
        }
        
        public DBConnectionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBConnectionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSum(int a, int b) {
            return base.Channel.GetSum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetSumAsync(int a, int b) {
            return base.Channel.GetSumAsync(a, b);
        }
        
        public int GetDiff(int a, int b) {
            return base.Channel.GetDiff(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetDiffAsync(int a, int b) {
            return base.Channel.GetDiffAsync(a, b);
        }
        
        public string GetTableData() {
            return base.Channel.GetTableData();
        }
        
        public System.Threading.Tasks.Task<string> GetTableDataAsync() {
            return base.Channel.GetTableDataAsync();
        }
        
        public int signUpUser(string name, string login, string password) {
            return base.Channel.signUpUser(name, login, password);
        }
        
        public System.Threading.Tasks.Task<int> signUpUserAsync(string name, string login, string password) {
            return base.Channel.signUpUserAsync(name, login, password);
        }
        
        public Client.ClientService.User SignInUser(string login, string password) {
            return base.Channel.SignInUser(login, password);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.User> SignInUserAsync(string login, string password) {
            return base.Channel.SignInUserAsync(login, password);
        }
        
        public Client.ClientService.Crossword[] getCrosswords(int offset, int count) {
            return base.Channel.getCrosswords(offset, count);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.Crossword[]> getCrosswordsAsync(int offset, int count) {
            return base.Channel.getCrosswordsAsync(offset, count);
        }
        
        public int createCrossword(Client.ClientService.Crossword cw) {
            return base.Channel.createCrossword(cw);
        }
        
        public System.Threading.Tasks.Task<int> createCrosswordAsync(Client.ClientService.Crossword cw) {
            return base.Channel.createCrosswordAsync(cw);
        }
        
        public string[] getThemes() {
            return base.Channel.getThemes();
        }
        
        public System.Threading.Tasks.Task<string[]> getThemesAsync() {
            return base.Channel.getThemesAsync();
        }
        
        public Client.ClientService.Crossword[] getUserCrosswords(int id, int offset, int length) {
            return base.Channel.getUserCrosswords(id, offset, length);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.Crossword[]> getUserCrosswordsAsync(int id, int offset, int length) {
            return base.Channel.getUserCrosswordsAsync(id, offset, length);
        }
        
        public int insertQuestions(Client.ClientService.QuestionAnswer[] items, int owner_id) {
            return base.Channel.insertQuestions(items, owner_id);
        }
        
        public System.Threading.Tasks.Task<int> insertQuestionsAsync(Client.ClientService.QuestionAnswer[] items, int owner_id) {
            return base.Channel.insertQuestionsAsync(items, owner_id);
        }
        
        public Client.ClientService.QuestionAnswer[] getCrosswordQuestions(int crosswirdID) {
            return base.Channel.getCrosswordQuestions(crosswirdID);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.QuestionAnswer[]> getCrosswordQuestionsAsync(int crosswirdID) {
            return base.Channel.getCrosswordQuestionsAsync(crosswirdID);
        }
        
        public void saveUsersCoins(long userId, int coins) {
            base.Channel.saveUsersCoins(userId, coins);
        }
        
        public System.Threading.Tasks.Task saveUsersCoinsAsync(long userId, int coins) {
            return base.Channel.saveUsersCoinsAsync(userId, coins);
        }
        
        public Client.ClientService.Crossword[] filterCrosswordsByTheme(int offset, int count, int themeId) {
            return base.Channel.filterCrosswordsByTheme(offset, count, themeId);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.Crossword[]> filterCrosswordsByThemeAsync(int offset, int count, int themeId) {
            return base.Channel.filterCrosswordsByThemeAsync(offset, count, themeId);
        }
        
        public Client.ClientService.Crossword[] findCrosswords(int offset, int count, string crosswordName) {
            return base.Channel.findCrosswords(offset, count, crosswordName);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.Crossword[]> findCrosswordsAsync(int offset, int count, string crosswordName) {
            return base.Channel.findCrosswordsAsync(offset, count, crosswordName);
        }
        
        public Client.ClientService.Crossword[] filterUserCrosswordsByTheme(int id, int offset, int length, int themeId) {
            return base.Channel.filterUserCrosswordsByTheme(id, offset, length, themeId);
        }
        
        public System.Threading.Tasks.Task<Client.ClientService.Crossword[]> filterUserCrosswordsByThemeAsync(int id, int offset, int length, int themeId) {
            return base.Channel.filterUserCrosswordsByThemeAsync(id, offset, length, themeId);
        }
        
        public int countCrosswords() {
            return base.Channel.countCrosswords();
        }
        
        public System.Threading.Tasks.Task<int> countCrosswordsAsync() {
            return base.Channel.countCrosswordsAsync();
        }
    }
}
